
Region.create(nombre: "Región de Magallanes y de la Antártica Chilena")
Comuna.create(nombre: "Iquique", code: "01101", provincia: "Iquique", region_id: Region.find_by(nombre: "Región de Tarapacá").id)
Comuna.create(nombre: "Alto Hospicio", code: "01102", provincia: "Iquique", region_id: Region.find_by(nombre: "Región de Tarapacá").id)
Comuna.create(nombre: "Pozo Almonte", code: "01201", provincia: "Tamarugal", region_id: Region.find_by(nombre: "Región de Tarapacá").id)
Comuna.create(nombre: "Camiña", code: "01402", provincia: "Tamarugal", region_id: Region.find_by(nombre: "Región de Tarapacá").id)
Comuna.create(nombre: "Colchane", code: "01403", provincia: "Tamarugal", region_id: Region.find_by(nombre: "Región de Tarapacá").id)
Comuna.create(nombre: "Huara", code: "01404", provincia: "Tamarugal", region_id: Region.find_by(nombre: "Región de Tarapacá").id)
Comuna.create(nombre: "Pica", code: "01405", provincia: "Tamarugal", region_id: Region.find_by(nombre: "Región de Tarapacá").id)
Comuna.create(nombre: "Antofagasta", code: "02101", provincia: "Antofagasta", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "Mejillones", code: "02102", provincia: "Antofagasta", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "Sierra Gorda", code: "02103", provincia:   "Antofagasta", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "Taltal", code: "02104", provincia: "Antofagasta", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "Calama", code: "02201", provincia: "El Loa", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "Ollagüe", code: "02202", provincia: "El Loa", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "San Pedro de Atacama", code: "02203", provincia: "El Loa", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "Tocopilla", code: "02301", provincia: "Tocopilla", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "María Elena", code: "02302", provincia: "Tocopilla", region_id: Region.find_by(nombre: "Región de Antofagasta").id)
Comuna.create(nombre: "Copiapó", code: "03101", provincia: "Copiapó", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Caldera", code: "03102", provincia: "Copiapó", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Tierra Amarilla", code: "03103", provincia: "Copiapó", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Chañaral", code: "03201", provincia: "Chañaral", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Diego de Almagro", code: "03202", provincia: "Chañaral", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Vallenar", code: "03301", provincia: "Huasco", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Alto del Carmen", code: "03302", provincia: "Huasco", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Freirina", code: "03303", provincia: "Huasco", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "Huasco", code: "03304", provincia: "Huasco", region_id: Region.find_by(nombre: "Región de Atacama").id)
Comuna.create(nombre: "La Serena", code: "04101", provincia: "Elqui", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Coquimbo", code: "04102", provincia: "Elqui", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Andacollo", code: "04103", provincia: "Elqui", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "La Higuera", code: "04104", provincia: "Elqui", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Paiguano", code: "04105", provincia: "Elqui", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Vicuña", code: "04106", provincia: "Elqui", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Illapel", code: "04201", provincia: "Choapa", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Canela", code: "04202", provincia: "Choapa", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Los Vilos", code: "04203", provincia: "Choapa", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Salamanca", code: "04204", provincia: "Choapa", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Ovalle", code: "04301", provincia: "Limarí", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Combarbalá", code: "04302", provincia: "Limarí", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Monte Patria", code: "04303", provincia: "Limarí", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Punitaqui", code: "04304", provincia: "Limarí", region_id: Region.find_by(nombre: "Región de Coquimbo").id)
Comuna.create(nombre: "Río Hurtado", code: "04305", provincia: "Limarí", region_id: Region.find_by(nombre: "Región de Coquimbo",).id)
Comuna.create(nombre: "Valparaiso", code: "05101", provincia: "Valparaiso", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Casablanca", code: "05102", provincia: "Valparaiso", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Concón", code: "05103", provincia: "Valparaiso", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Juan Fernández", code: "05104", provincia: "Valparaiso", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Puchuncaví", code: "05105", provincia: "Valparaiso", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Quintero", code: "05107", provincia: "Valparaiso", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Viña del Mar", code: "05109", provincia: "Valparaiso", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Isla de Pascua", code: "05201", provincia: "Isla de Pascua", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Los Andes", code: "05301", provincia: "Los Andes", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Calle Larga", code: "05302", provincia: "Los Andes", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Riconada", code: "05303", provincia: "Los Andes", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "San Esteban", code: "05304", provincia: "Los Andes", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "La Ligua", code: "05401", provincia: "Petorca", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Cabildo", code: "05402", provincia: "Petorca", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Papudo", code: "05403", provincia: "Petorca", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Petorca", code: "05404", provincia: "Petorca", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Zapallar", code: "05405", provincia: "Petorca", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Quillota", code: "05501", provincia: "Quillota", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Calera", code: "05502", provincia: "Quillota", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Hijuelas", code: "05503", provincia: "Quillota", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "La Cruz", code: "05504", provincia: "Quillota", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Nogales", code: "05506", provincia: "Quillota", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "San Antonio", code: "05601", provincia: "San Antonio", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Algarrobo", code: "05602", provincia: "San Antonio", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Cartagena", code: "05603", provincia: "San Antonio", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "El Quisco", code: "05604", provincia: "San Antonio", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "El Tabo", code: "05605", provincia: "San Antonio", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Santo Domingo", code: "05606", provincia: "San Antonio", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "San Felipe", code: "05701", provincia: "San Felipe de Aconcagua", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Catemu", code: "05702", provincia: "San Felipe de Aconcagua", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Llaillay", code: "05703", provincia: "San Felipe de Aconcagua", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Panquehue", code: "05704", provincia: "San Felipe de Aconcagua", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Putaendo", code: "05705", provincia: "San Felipe de Aconcagua", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Santa María", code: "05706", provincia: "San Felipe de Aconcagua", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Quilpué", code: "05801", provincia: "Marga Marga", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Limache", code: "05802", provincia: "Marga Marga", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Olmué", code: "05803", provincia: "Marga Marga", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Villa Alemana", code: "05804", provincia: "Marga Marga", region_id: Region.find_by(nombre: "Región de Valparaiso").id)
Comuna.create(nombre: "Rancagua", code: "06101", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Codegua", code: "06102", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Coinco", code: "06103", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Coltauco", code: "06104", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Doñihue", code: "06105", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Graneros", code: "06106", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Las Cabras", code: "06107", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Machalí", code: "06108", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Malloa", code: "06109", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Mostazal", code: "06110", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Olivar", code: "06111", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Peumo", code: "06112", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Pichidegua", code: "06113", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Quinta de Tilcoco", code: "06114", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Rengo", code: "06115", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Requínoa", code: "06116", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "San Vicente", code: "06117", provincia: "Cachapoal", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Pichilemu", code: "06201", provincia: "Cardenal Caro", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "La Estrella", code: "06202", provincia: "Cardenal Caro", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Litueche", code: "06203", provincia: "Cardenal Caro", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Marichihue", code: "06204", provincia: "Cardenal Caro", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Navidad", code: "06205", provincia: "Cardenal Caro", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Paredones", code: "06206", provincia: "Cardenal Caro", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "San Fernando", code: "06301", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Chépica", code: "06302", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Chimbarongo", code: "06303", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Lolol", code: "06304", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Nancagua", code: "06305", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Palmilla", code: "06306", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Peralillo", code: "06307", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Placilla", code: "06308", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Pumanque", code: "06309", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Santa Cruz", code: "06310", provincia: "Colchagua", region_id: Region.find_by(nombre: "Región del Libertador Gral. Bernardo O'Higgins").id)
Comuna.create(nombre: "Talca", code: "07101", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Constitución", code: "07102", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Curepto", code: "07103", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Empedrado", code: "07104", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Maule", code: "07105", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Pelarco", code: "07106", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Pencahue", code: "07107", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Río Claro", code: "07108", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "San Clemente", code: "07109", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "San Rafael", code: "07110", provincia: "Talca", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Cauquenes", code: "07201", provincia: "Cauquenes", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Chanco", code: "07202", provincia: "Cauquenes", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Pelluhue", code: "07203", provincia: "Cauquenes", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Curicó", code: "07301", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Hualañé", code: "07302", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Licantén", code: "07303", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Molina", code: "07304", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Rauco", code: "07305", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Romeral", code: "07306", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Sagrada Familia", code: "07307", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Teno", code: "07308", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Vichuquén", code: "07309", provincia: "Curicó", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Linares", code: "07401", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Colbún", code: "07402", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Longaví", code: "07403", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Parral", code: "07404", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Retiro", code: "07405", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "San Javier", code: "07406", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Villa Alegre", code: "07407", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Yerbas Buenas", code: "07408", provincia: "Linares", region_id: Region.find_by(nombre: "Región del Maule").id)
Comuna.create(nombre: "Concepción", code: "08101", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Coronel", code: "08102", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Chiguayante", code: "08103", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Florida", code: "08104", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Hualqui", code: "08105", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Lota", code: "08106", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Penco", code: "08107", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "San Pedro de la Paz", code: "08108", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Santa Juana", code: "08109", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Talcahuano", code: "08110", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Tomé", code: "08111", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Hualpén", code: "08112", provincia: "Concepción", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Lebu", code: "08201", provincia: "Arauco", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Arauco", code: "08202", provincia: "Arauco", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Cañete", code: "08203", provincia: "Arauco", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Contulmo", code: "08204", provincia: "Arauco", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Curanilahue", code: "08205", provincia: "Arauco", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Los Álamos", code: "08206", provincia: "Arauco", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Tirúa", code: "08207", provincia: "Arauco", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Los Ángeles", code: "08301", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Antuco", code: "08302", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Cabrero", code: "08303", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Laja", code: "08304", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Mulchén", code: "08305", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Nacimiento", code: "08306", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Negrete", code: "08307", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Quilaco", code: "08308", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Quilleco", code: "08309", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "San Rosendo", code: "08310", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Santa Bárbara", code: "08311", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Tucapel", code: "08312", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Yumbel", code: "08313", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Alto Biobío", code: "08314", provincia: "Biobío", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Chillán", code: "08401", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Bulnes", code: "08402", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Cobquecura", code: "08403", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Coelemu", code: "08404", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Coihueco", code: "08405", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Chillán Viejo", code: "08406", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "El Carmen", code: "08407", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Ninhue", code: "08408", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Ñiquén", code: "08409", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Pemuco", code: "08410", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Pinto", code: "08411", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Portezuelo", code: "08412", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Quillón", code: "08413", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Quirihue", code: "08414", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Ránquil", code: "08415", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "San Carlos", code: "08416", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "San Fabián", code: "08417", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "San Ignacio", code: "08418", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "San Nicolás", code: "08419", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Treguaco", code: "08420", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Yungay", code: "08421", provincia: "Ñuble", region_id: Region.find_by(nombre: "Región del Biobío").id)
Comuna.create(nombre: "Temuco", code: "09101", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Carahu", code: "09102", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Cunco", code: "09103", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Curarrehue", code: "09104", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Freire", code: "09105", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Galvarin", code: "09106", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Gorbea", code: "09107", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Lautaro", code: "09108", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Loncoche", code: "09109", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Melipeuco", code: "09110", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Nueva Imperial", code: "09111", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Padre las Casa", code: "09112", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Perquenco", code: "09113", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Pitrufquén", code: "09114", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Pucó", code: "09115", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Saavedra", code: "09116", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Teodoro Schmid", code: "09117", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Toltén", code: "09118", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Vilcún", code: "09119", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Villarrica", code: "09120", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Cholchol", code: "09121", provincia: "Cautín", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Angol", code: "09201", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Collipulli", code: "09202", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Curacautín", code: "09203", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Ercilla", code: "09204", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Lonquimay", code: "09205", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Los Sauces", code: "09206", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Lumaco", code: "09207", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Purén", code: "09208", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Renaico", code: "09209", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Traiguén", code: "09210", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Victoria", code: "09211", provincia: "Malleco", region_id: Region.find_by(nombre: "Región de la Araucanía").id)
Comuna.create(nombre: "Valdivia", code: "14101", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Corral", code: "14102", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Lanco", code: "14103", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Los Lagos", code: "14104", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Máfil", code: "14105", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Mariquina", code: "14106", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Paillaco", code: "14107", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Panguipulli", code: "14108", provincia: "Valdivia", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "La Unión", code: "14201", provincia: "Ranco", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Futrono", code: "14201", provincia: "Ranco", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Lago Ranco", code: "14201", provincia: "Ranco", region_id: Region.find_by(nombre: "Región de los Ríos").id)
Comuna.create(nombre: "Río Bueno", code: "14201", provincia: "Ranco", region_id: Region.find_by(nombre: "Región de los Ríos", ).id)
Comuna.create(nombre: "Puerto Montt", code: "10101", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Calbuco", code: "10102", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Cochamó", code: "10103", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Fresia", code: "10104", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Frutillar", code: "10105", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Los Muermos", code: "10106", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Llanquihue", code: "10107", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Maullín", code: "10108", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Puerto Varas", code: "10109", provincia: "Llanquihue", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Castro", code: "10201", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Ancud", code: "10202", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Chonchi", code: "10203", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Curaco de Vélez", code: "10204", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Dalcahue", code: "10205", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Puqueldón", code: "10206", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Queilén", code: "10207", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Quellón", code: "10208", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Quemchi", code: "10209", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Quinchao", code: "10210", provincia: "Chiloé", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Osorno", code: "10301", provincia: "Osorno", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Puerto Octay", code: "10302", provincia: "Osorno", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Purranque", code: "10303", provincia: "Osorno", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Puyehue", code: "10304", provincia: "Osorno", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Río Negro", code: "10305", provincia: "Osorno", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "San Juan de la Costa", code: "10306", provincia: "Osorno", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "San Pablo", code: "10307", provincia: "Osorno", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Chaitén", code: "10401", provincia: "Palena", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Futaleufú", code: "10402", provincia: "Palena", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Hualaihué", code: "10403", provincia: "Palena", region_id: Region.find_by(nombre: "Región de los Lagos").id)
Comuna.create(nombre: "Coihaique", code: "11101", provincia: "Coihaique", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Lago Verde", code: "11102", provincia: "Coihaique", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Aisén", code: "11201", provincia: "Aisén", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Cisnes", code: "11202", provincia: "Aisén", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Guaitecas", code: "11203", provincia: "Aisén", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Cochrane", code: "11301", provincia: "Capitán Pratt", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "O’Higgins", code: "11302", provincia: "Capitán Pratt", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Tortel", code: "11303", provincia: "Capitán Pratt", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Chile Chico", code: "11401", provincia: "General Carrera", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Río Ibáñez", code: "11402", provincia: "General Carrera", region_id: Region.find_by(nombre: "Región Aisén del Gral. Carlos Ibañez del Campo").id)
Comuna.create(nombre: "Punta Arenas", code: "12101", provincia: "Magallanes", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Laguna Blanca", code: "12102", provincia: "Magallanes", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Río Verde", code: "12103", provincia: "Magallanes", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "San Gregorio", code: "12104", provincia: "Magallanes", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Cabo de Hornos", code: "12201", provincia: "Antártica Chilena", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Antártica", code: "12202", provincia: "Antártica Chilena", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Porvenir", code: "12301", provincia: "Tierra del Fuego", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Primavera", code: "12302", provincia: "Tierra del Fuego", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Timaukel", code: "12303", provincia: "Tierra del Fuego", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Natales", code: "12401", provincia: "Última Esperanza", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
Comuna.create(nombre: "Torres del Paine", code: "12402", provincia: "Última Esperanza", region_id: Region.find_by(nombre: "Región de Magallanes y de la Antártica Chilena").id)
